coverage gate test

diff --git a/buildspec.yml b/buildspec.yml
--- a/buildspec.yml
+++ b/buildspec.yml
@@ -9,19 +9,22 @@ phases:
     commands:
       - echo "Instalando dependencias..."
       - go get -t -v ./...
-
       - echo "Ejecutando pruebas..."
-      # - go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.57.2
-      # - golangci-lint run
-      - go install github.com/patrickhoefler/gocovergate@latest
-      - go test . -coverprofile cover.out
-      - gocovergate
-      - go test . -coverprofile coverage-report
-      - go tool cover -html coverage-report -o coverage-report.html
+      - go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.57.2
+      - golangci-lint run
+      - go test . -coverprofile coverage-report  # Genera el informe de cobertura
+      - go tool cover -html coverage-report -o coverage-report.html  # Genera reporte HTML
       - go install github.com/jstemmer/go-junit-report/v2@latest
       - go test -v 2>&1 . | go-junit-report -set-exit-code > reports/report.xml
       - echo "Compilando la aplicación..."
       - go build -o application
+
+      # Verificar cobertura y fallar si es menor a 80%
+      - grep -Eo '[0-9]+\.[0-9]+' coverage-report | tail -n 1 > coverage_percent.txt
+      - if [ $(cat coverage_percent.txt) -lt 80 ]; then
+          echo "Error: Cobertura de pruebas menor al 80%"
+          exit 1  # Marca la compilación como fallida
+        fi
 
 reports:
   coverage-report:
